services:
  - type: web
    runtime: docker
    name: makaron-music-library-api
    region: singapore
    plan: starter
    healthCheckPath: /v1/health
    autoDeployTrigger: "off"
    maxShutdownDelaySeconds: 30
    envVars:
      - key: MUSICLIB_SERVER_TOKEN
        sync: false
      - key: MUSICLIB_LIBRARY
        value: /data/library
      - key: MUSICLIB_NAME
        value: Makaron Central Music Library
    disk:
      name: music-library-data
      mountPath: /data
      sizeGB: 10
